adding migrations check

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -94,7 +94,12 @@ jobs:
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/final_project_react_image:latest
 
   Copy-docker-compose-to-EC2:
-    needs: test
+    needs:
+      [
+        build-and-push-react-image,
+        build-and-push-laravel-image,
+        Copy-docker-compose-to-EC2,
+      ]
     runs-on: ubuntu-latest
 
     steps:
@@ -122,12 +127,7 @@ jobs:
 
   Deploy-Laravel-Docker:
     runs-on: ubuntu-latest
-    needs:
-      [
-        build-and-push-react-image,
-        build-and-push-laravel-image,
-        Copy-docker-compose-to-EC2,
-      ]
+    needs: Copy-docker-compose-to-EC2
 
     steps:
       - name: Checkout repository
@@ -177,6 +177,13 @@ jobs:
 
             # Run migrations
             docker exec $BACKEND_CONTAINER php artisan migrate --force
+
+            # If fails, show error logs
+            if [ $? -ne 0 ]; then
+              echo "Migration failed! Showing logs:"
+              docker logs $BACKEND_CONTAINER | grep -i error
+              exit 1
+            fi
 
             # Clean up unused images
             docker image prune -a -f
